manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: eyelash-peripherals
      url-base: https://github.com/a741725193
      # Additional modules containing boards/shields/custom code can be listed here as well.
      # See:
      # - https://zmk.dev/docs/features/modules
      # - https://docs.zephyrproject.org/3.5.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: eyelash_corne
      remote: eyelash-peripherals
      revision: 6bbe04d43307756b1a54d7576229a226d70201c1
  self:
    path: config
